markdown: GFM

title: coder114514的个人网站

locale: "zh-CN"

lang: zh-CN,en-US

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

date_format: "%Y/%m/%d"

permalink: /old_blogs/:year/:month/:day/:title:output_ext

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      classes: wide

search: true

tag_archive:
  type: liquid
  path: /old_blogs/by_tags.html
