markdown: GFM

title: 博客

locale: "zh-CN"

lang: zh-CN,en-US

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: dark

date_format: "%Y/%m/%d"

repository: coder114514/coder114514.github.io

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      comments: true

comments:
  provider: "giscus"
  giscus:
    repo_id              : R_kgDOIao9sQ
    category_name        : Comments
    category_id          : DIC_kwDOIao9sc4CUCOU
    discussion_term      : og:title
    reactions_enabled    : 1
    theme                : preferred_color_scheme
