markdown: GFM
title: 博客
locale: "zh-CN"
lang: zh-CN,en-US
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: dark
plugins:
- jekyll-remote-theme
- jekyll-include-cache
- jekyll-sitemap
