markdown: GFM

title: coder114514的博客

locale: "zh-CN"

lang: zh-CN,en-US

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "air"

date_format: "%Y/%m/%d"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      classes: wide

search: true

category_archive:
  type: liquid
  path: /by_categories.html

tag_archive:
  type: liquid
  path: /by_tags.html
